// examples/astro-multi-framework/src/components/vue/Card.vue
<script setup>
import {useStore} from '@nanostores/vue';
import {homeBannerStore} from '../state';

const store = useStore(homeBannerStore);
</script>

<template>
  <div class="card">
    <div style="align: center">Vue</div>
    <h1>{{store.content.title}}</h1>
    <div class="text"><strong>{{store.content.subtitle}}</strong></div>
    <p>
      <a href="{{store.content.cta.link}}">{{store.content.cta.label}}</a>
    </p>
  </div>
</template>

// examples/astro-multi-framework/src/components/react/Card.tsx
import {useStore} from '@nanostores/react';
import React from 'react';
import {homeBannerStore} from '../state';

export function ReactCard(): React.JSX.Element {
    const {content} = useStore(homeBannerStore);

    return (
        <div className="card">
            <div style={{align: 'center'}}>React</div>
            <h1>{content.title}</h1>
            <div className="text"><strong>{content.subtitle}</strong></div>
            <p>
                <a href={content.cta.link}>{content.cta.label}</a>
            </p>
        </div>
    );
}
